# Generated by Django 2.2.19 on 2023-10-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=1, help_text='Добавьте категорию блюда.', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='catalog.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
